### ISSUE TITLE
nbsp for product names

### ISSUE THREAD

**Issue by mishaone** [redhat-documentation/asciidoc-markup-conventions#24]
The company name and product name guidelines indicate no special markup, but we should have a non-breaking space markup recommended. I believe the guidelines in the past were something like this:

Red&nbsp;Hat Enterprise&nbsp;Linux

**Comment by rkratky** [comment]
@mishaone, good point. I don't see the mark-up you used for RHEL above, but I suspect it's this, right?
```
Red{nbsp}Hat Enterprise{nbsp}Linux
```
Trouble is that there are so many products, it would be impractical to list them all in this doc. Can we get by with a general recommendation?

**Comment by mishaone** [comment]
Absolutely, Robert. I think one example to illustrate it is fine and then people can apply as relevant to thier own products. As long as things like Red and Hat being on different lines or the product name doing the same is avoided, we should be fine.

**Comment by rkratky** [comment]
Could you please submit a PR to that effect?

**Comment by mishaone** [comment]
Done, needs review+merge: https://github.com/redhat-documentation/asciidoc-markup-conventions/pull/26
