### ISSUE TITLE
Use of Italics for "System or software variable to be replaced by the user"

### ISSUE THREAD

**Issue by tylerkelly13** [redhat-documentation/asciidoc-markup-conventions#25]
Use of Italics for "System or software variable to be replaced by the user" and "System or software configuration parameter or environment variable" may lead to confusion.

Recommend reviewing this convention.

**Comment by michellemurray** [comment]
++1

**Comment by gaurav-nelson** [comment]
+1

**Comment by rkratky** [comment]
What do you suggest?

**Comment by tylerkelly13** [comment]
I suggest using _&#60;variable&#62;_ to make the replaceable more obvious to the user. this is the convention used in openshift docs, as well as some middleware products

**Comment by rkratky** [comment]
@tylerkelly13 by that you mean mandating the enclosing of the value in `<>`?

**Comment by tylerkelly13** [comment]
Yes, it helps replaceable code stand out more for the user. Some of our code (possibly most) can be copied and pasted from our docs into a terminal and run without modification. It's important emphasize code that needs modification before being run.

**Comment by swadeley** [comment]
Using <>  around a replaceable would be double markup when using italics. Leave them for manual pages.

Re:  configuration parameter or environment variable

I agree they should not be in italics.  If these are in capitals, such as directives, then no markup is required, but no strong objection to `` for these.

I have been using `` for commands as we already use ** for GUI labels.

**Comment by bergerhoffer** [comment]
Closing this issue as the replaceable value guidance has been evaluated by the supplementary style guide project, and the effort to update this guide is being handled in #36.
