### ISSUE TITLE
Incorrect example of emphasis for a term 	

### ISSUE THREAD

**Issue by melcorr** [redhat-documentation/asciidoc-markup-conventions#29]
In the current guide it has the following example: 

Emphasis for a term | Use _this_ approach. -- | --

I don't think we should ever use italics to emphasise a word like 'this'. I cannot think of a scenario where this would be a legitimate use case. 

If we are adding italics, we should be doing so in accordance with the IBM Style Guide. 

For example, when you define a new term, the word you are defining can be in italics. 

I suggest either deleting this guidance, or rewriting with an example from IBM Style Guide.

**Comment by rkratky** [comment]
The word 'this' is not used as an example of what should be emphasized but how. I.e. the significant thing is that it is rendered in italics, not what the actual word is.

Still, I understand that it can be misinterpreted, so it should be changed. Please, submit a PR to fix it.

**Comment by yetanothertw** [comment]
+1 to this issue, the current example is vague and weak and leaves it open to interpretation; it needs to be rewritten.

**Comment by bergerhoffer** [comment]
Submitted PR #39 to add a different example for the emphasis entry. 

@rkratky As we discussed a few months ago, we need to keep this guide up to date if we want to keep pointing writers to it. I know that our original project team that worked on this has kind of disbanded. Do you have any thoughts on how we want to revive this and make sure that issues being raised are addressed in a timely manner (and approved by more than 1 person)?
