### ISSUE TITLE
{nbsp} in Command Block

### ISSUE THREAD

**Issue by apinnick** [redhat-documentation/asciidoc-markup-conventions#32]
{nbsp} in a command block does not render correctly unless the block is preceded by [subs="attributes"], as in the following example:

[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# ansible-playbook --private-key=/etc/pki/ovirt-engine/keys/engine_id_rsa -i /usr/share/ovirt-engine-metrics/bin/ovirt-engine-hosts-ansible-inventory --extra-vars "{nbsp}cluster_name=_Cluster_Name_ ovn_central=_OVN_Central_IP_ ovn_tunneling_interface=_VDSM_Network_Name_" ovirt-provider-ovn-driver.yml
----

**Comment by VladimirSlavik** [comment]
I'd say this particular issue is not with the conventions, but with the insufficient documentation for markup inside command blocks.

That said, I'd love to have some reference for the command block shenanigans, too - it's a rater murky topic. Even the official AsciiDoc(tor?) manual does not say enough.
