### ISSUE TITLE
Update the 'Reference to Red Hat guides' example

### ISSUE THREAD

**Issue by yetanothertw** [redhat-documentation/asciidoc-markup-conventions#35]
This example doesn't follow the conventions for references that outlined in the IBM Style Guide (see Citations and references, General guidelines).

I suggest rewording the example 
from: See the JBoss EAP _Getting Started Guide_ for more information.
to: For more information, see the JBoss EAP _Getting Started Guide_.

**Comment by bergerhoffer** [comment]
Submitted PR #41 to rearrange the wording to follow the ISG. Also added a real link so that the example link doesn't 404.
