### ISSUE TITLE
Update the 'System or software variable to be replaced by the user' example ad markup used

### ISSUE THREAD

**Issue by yetanothertw** [redhat-documentation/asciidoc-markup-conventions#36]
According to the RH Supplementary Style Guide (https://redhat-documentation.github.io/supplementary-style-guide/#user-replaced-values) this example should be updated to reflect the following guidelines.

Ensure that user-replaced values have the following characteristics:
* Surrounded by angle brackets (< >)
* Separated by underscores (_) for multi-word values
* Lowercase, unless the rest of the related text is uppercase or another capitalization scheme
* Italicized
* If the user-replaced value is referencing a value in code or in a command that is normally monospace, also use monospace for the user-replaced value.

Example AsciiDoc: User-replaced value in a paragraph
Create an Ansible inventory file that is named `/_<path>_/inventory/hosts`.

Suggested change 
from: Use the following command to roll back a deployment, specifying the deployment name: `oc rollback _deployment_`.
to: Use the following command to roll back a deployment, specifying the deployment name: `oc rollback _<deployment>_`.
alternative suggestion: To roll back a deployment, specify the deployment name: `oc rollback _<deployment>_`.

**Comment by bergerhoffer** [comment]
Submitted PR #40 to update example to match the supplementary style guide guidance.
