### ISSUE TITLE
Update the 'Anchor' example

### ISSUE THREAD

**Issue by yetanothertw** [redhat-documentation/asciidoc-markup-conventions#37]
The example must be update to reflect the latest Mod docs conventions as per the Modular Documentation Reference Guide: https://redhat-documentation.github.io/modular-docs/

From: [id="section-header_{context}"] 

To: [id="proc-section-header_{context}"] 
or [id="ref-section-header_{context}"] 
or [id="con-section-header_{context}"] 
or even [id="assembly-section-header_{context}"]

**Comment by bergerhoffer** [comment]
If I understand the mod docs guidance correctly, the anchor names are supposed to match the file names, per the description from https://github.com/redhat-documentation/modular-docs/pull/121:

> Anchor names should match files names without the .adoc extension, and with the addition of _{context}.

And it is optional to use `proc` or `con` or `ref` as a prefix in your file names. Teams can alternatively use the option to define the `:_module-type:` variable in the file. So I don't think that we'd necessarily want to require this here in the general anchor format.

**Comment by yetanothertw** [comment]
Fair point @bergerhoffer I only became aware of the `:_module-type:` variable last week. I hadn't realised that using proc, con, ref or assembly is optional. Thanks for pointing this out! :)

**Comment by bergerhoffer** [comment]
@yetanothertw I'm closing this issue because I don't think there is any required action, but feel free to reopen if there is!
