### ISSUE TITLE
Typo (I think) in GUI Menu example

### ISSUE THREAD

**Issue by sterobin** [redhat-documentation/asciidoc-markup-conventions#5]
Says this: 
Navigate to menu:File[Import>Import csv] to import a csv file.

But I think should be this: 
Navigate to menu:[File>Import>Import csv] to import a csv file.

Right?

**Comment by rkratky** [comment]
I don't think so. See http://asciidoctor.org/docs/user-manual/#menu-selections

**Comment by sterobin** [comment]
Oh weird, you're right @rkratky. My bad.

Closing this issue.
