### ISSUE TITLE
Add note about :experimental:

### ISSUE THREAD

**Issue by rkratky** [redhat-documentation/asciidoc-markup-conventions#9]
A note needs to be added that the `:experimental:` attribute must be enabled for the mark-up to work properly.

I believe it's enabled by default in ccutil/Pantheon (check!), but local AsciiDoctor or CI Jenkins previews, wouldn't work w/o it.

**Comment by bergerhoffer** [comment]
I thought that @sgilda had added this note in one of her PRs. Is it possible this was lost when the repo was deleted?

**Comment by rkratky** [comment]
Fixed by #15
